// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	address "cosmossdk.io/core/address"

	cosmos_sdktypes "github.com/cosmos/cosmos-sdk/types"

	mock "github.com/stretchr/testify/mock"
)

// AccountKeeper is an autogenerated mock type for the AccountKeeper type
type AccountKeeper struct {
	mock.Mock
}

type AccountKeeper_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountKeeper) EXPECT() *AccountKeeper_Expecter {
	return &AccountKeeper_Expecter{mock: &_m.Mock}
}

// AddressCodec provides a mock function with no fields
func (_m *AccountKeeper) AddressCodec() address.Codec {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddressCodec")
	}

	var r0 address.Codec
	if rf, ok := ret.Get(0).(func() address.Codec); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(address.Codec)
		}
	}

	return r0
}

// AccountKeeper_AddressCodec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddressCodec'
type AccountKeeper_AddressCodec_Call struct {
	*mock.Call
}

// AddressCodec is a helper method to define mock.On call
func (_e *AccountKeeper_Expecter) AddressCodec() *AccountKeeper_AddressCodec_Call {
	return &AccountKeeper_AddressCodec_Call{Call: _e.mock.On("AddressCodec")}
}

func (_c *AccountKeeper_AddressCodec_Call) Run(run func()) *AccountKeeper_AddressCodec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AccountKeeper_AddressCodec_Call) Return(_a0 address.Codec) *AccountKeeper_AddressCodec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountKeeper_AddressCodec_Call) RunAndReturn(run func() address.Codec) *AccountKeeper_AddressCodec_Call {
	_c.Call.Return(run)
	return _c
}

// GetModuleAccount provides a mock function with given fields: ctx, moduleName
func (_m *AccountKeeper) GetModuleAccount(ctx context.Context, moduleName string) cosmos_sdktypes.ModuleAccountI {
	ret := _m.Called(ctx, moduleName)

	if len(ret) == 0 {
		panic("no return value specified for GetModuleAccount")
	}

	var r0 cosmos_sdktypes.ModuleAccountI
	if rf, ok := ret.Get(0).(func(context.Context, string) cosmos_sdktypes.ModuleAccountI); ok {
		r0 = rf(ctx, moduleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cosmos_sdktypes.ModuleAccountI)
		}
	}

	return r0
}

// AccountKeeper_GetModuleAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModuleAccount'
type AccountKeeper_GetModuleAccount_Call struct {
	*mock.Call
}

// GetModuleAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - moduleName string
func (_e *AccountKeeper_Expecter) GetModuleAccount(ctx interface{}, moduleName interface{}) *AccountKeeper_GetModuleAccount_Call {
	return &AccountKeeper_GetModuleAccount_Call{Call: _e.mock.On("GetModuleAccount", ctx, moduleName)}
}

func (_c *AccountKeeper_GetModuleAccount_Call) Run(run func(ctx context.Context, moduleName string)) *AccountKeeper_GetModuleAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountKeeper_GetModuleAccount_Call) Return(_a0 cosmos_sdktypes.ModuleAccountI) *AccountKeeper_GetModuleAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountKeeper_GetModuleAccount_Call) RunAndReturn(run func(context.Context, string) cosmos_sdktypes.ModuleAccountI) *AccountKeeper_GetModuleAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetModuleAddress provides a mock function with given fields: moduleName
func (_m *AccountKeeper) GetModuleAddress(moduleName string) cosmos_sdktypes.AccAddress {
	ret := _m.Called(moduleName)

	if len(ret) == 0 {
		panic("no return value specified for GetModuleAddress")
	}

	var r0 cosmos_sdktypes.AccAddress
	if rf, ok := ret.Get(0).(func(string) cosmos_sdktypes.AccAddress); ok {
		r0 = rf(moduleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cosmos_sdktypes.AccAddress)
		}
	}

	return r0
}

// AccountKeeper_GetModuleAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModuleAddress'
type AccountKeeper_GetModuleAddress_Call struct {
	*mock.Call
}

// GetModuleAddress is a helper method to define mock.On call
//   - moduleName string
func (_e *AccountKeeper_Expecter) GetModuleAddress(moduleName interface{}) *AccountKeeper_GetModuleAddress_Call {
	return &AccountKeeper_GetModuleAddress_Call{Call: _e.mock.On("GetModuleAddress", moduleName)}
}

func (_c *AccountKeeper_GetModuleAddress_Call) Run(run func(moduleName string)) *AccountKeeper_GetModuleAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AccountKeeper_GetModuleAddress_Call) Return(_a0 cosmos_sdktypes.AccAddress) *AccountKeeper_GetModuleAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountKeeper_GetModuleAddress_Call) RunAndReturn(run func(string) cosmos_sdktypes.AccAddress) *AccountKeeper_GetModuleAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetSequence provides a mock function with given fields: _a0, _a1
func (_m *AccountKeeper) GetSequence(_a0 context.Context, _a1 cosmos_sdktypes.AccAddress) (uint64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSequence")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cosmos_sdktypes.AccAddress) (uint64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cosmos_sdktypes.AccAddress) uint64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, cosmos_sdktypes.AccAddress) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountKeeper_GetSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSequence'
type AccountKeeper_GetSequence_Call struct {
	*mock.Call
}

// GetSequence is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 cosmos_sdktypes.AccAddress
func (_e *AccountKeeper_Expecter) GetSequence(_a0 interface{}, _a1 interface{}) *AccountKeeper_GetSequence_Call {
	return &AccountKeeper_GetSequence_Call{Call: _e.mock.On("GetSequence", _a0, _a1)}
}

func (_c *AccountKeeper_GetSequence_Call) Run(run func(_a0 context.Context, _a1 cosmos_sdktypes.AccAddress)) *AccountKeeper_GetSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(cosmos_sdktypes.AccAddress))
	})
	return _c
}

func (_c *AccountKeeper_GetSequence_Call) Return(_a0 uint64, _a1 error) *AccountKeeper_GetSequence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountKeeper_GetSequence_Call) RunAndReturn(run func(context.Context, cosmos_sdktypes.AccAddress) (uint64, error)) *AccountKeeper_GetSequence_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountKeeper creates a new instance of AccountKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountKeeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountKeeper {
	mock := &AccountKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
